server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url:  postgres://pqapnzmgxciaeq:42c4ab6f585f6244be3eafc228a830b00f03e2509e9b2fba06a9d1097079113e@ec2-34-232-191-133.compute-1.amazonaws.com:5432/dbgphoj4rn5gvk
    #username: postgres
    username: pqapnzmgxciaeq
    #password: 123456
    password: 42c4ab6f585f6244be3eafc228a830b00f03e2509e9b2fba06a9d1097079113e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander utilizando Java e Angular